[project]
name = "django-reactflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.9",
    "python-dotenv>=1.2.1",
]
